#
# Copyright (c) 2022 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#

[package]
name = "zenoh-flow-daemon"
version = "0.3.0"
repository = "https://github.com/eclipse-zenoh/zenoh-flow"
homepage = "http://zenoh.io"
authors = ["kydos <angelo@icorsaro.net>",
           "gabrik <gabriele.baldoni@gmail.com>",
           "Julien Loudet <julien.loudet@zettascale.tech>",]
edition = "2018"
license = " EPL-2.0 OR Apache-2.0"
categories = ["network-programming"]
description = "Zenoh-Flow: zenoh-based data-flow programming framework for computations that span from the cloud to the device."
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zenoh-flow = {path = "../zenoh-flow"}
env_logger = "0.9.0"
serde_derive = "1.0"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_yaml = {version = "0.8"}
serde_json = "1.0"
log = "0.4"
async-std = { version = "=1.11.0", features = ["attributes"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
uhlc = "0.5"
zenoh = { git = "https://github.com/eclipse-zenoh/zenoh.git", branch = "master"}
zenoh-util = { git = "https://github.com/eclipse-zenoh/zenoh.git", branch = "master" }
zrpc = { git = "https://github.com/atolab/zenoh-rpc.git", branch = "master" }
znrpc-macros = { git = "https://github.com/atolab/zenoh-rpc.git", branch = "master" }
clap = { version = "3.1", features = ["derive"] }
hostname = "0.3.1"
machine-uid = "0.2.0"
git-version = "0.3"
async-ctrlc ={version = "1.2.0", features = ["stream"]}
futures = "0.3.5"



# Debian package configuration

[package.metadata.deb]
maintainer = "ADLINK Zenoh team <zenoh@adlink-labs.tech>"
copyright = "2021, ADLINK Technology Inc"
extended-description = "Eclipse Zenoh Flow Daemon"
license-file = ["../LICENSE", "0"]
depends = "$auto"
section = "utils"
priority = "optional"
assets = [
    # binary
    ["target/release/zenoh-flow-daemon", "/usr/bin/zenoh-flow-daemon", "755"],
    # assets
    ["etc/runtime.yaml", "/etc/zenoh-flow/runtime.yaml", "644"],
    ["etc/zenoh-daemon.json","/etc/zenoh-flow/zenoh-daemon.json","644"],
    ["etc/zenoh-zf-router.json","/etc/zenoh-flow/zenoh-zf-router.json","644"],
    ["etc/extensions.d/placeholder", "/etc/zenoh-flow/extensions.d/placeholder", "644"],
    ["var/*", "/var/zenoh-flow", "644"],
]

conf-files = ["/etc/zenoh-flow/runtime.yaml"]

[package.metadata.deb.systemd-units]
unit-scripts = "resources/"
unit-name = "zenoh-flow.service"

# RPM package configuration

[package.metadata.rpm]
package = "zenoh-flow-daemon"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
zenoh-flow-daemon = { path = "/usr/bin/zenoh-flow-daemon" }

[package.metadata.rpm.files]
"../etc/runtime.yaml" = { path = "/etc/zenoh-flow/runtime.yaml", mode = "644" }
"../etc/zenoh-daemon.json" = { path = "/etc/zenoh-flow/zenoh-daemon.json", mode = "644" }
"../etc/zenoh--zf-router.json" = { path = "/etc/zenoh-flow/zenoh-zf-router.json", mode = "644" }
"../etc/extensions.d/placeholder" = { path = "/etc/zenoh-flow/extensions.d/placeholder", mode = "644" }
"../var/placeholder" = { path = "/var/zenoh-flow/placeholder" }
"../resources/zenoh-flow.service" = { path = "/lib/systemd/system/zenoh-flow.service" }
