[package]
name = "zfctl"
version = "0.2.0"
repository = "https://github.com/eclipse-zenoh/zenoh-flow"
homepage = "http://zenoh.io"
authors = ["kydos <angelo@icorsaro.net>",
           "gabrik <gabriele.baldoni@gmail.com>",
           "Julien Loudet <julien.loudet@adlinktech.com>",]
edition = "2018"
license = " EPL-2.0 OR Apache-2.0"
categories = ["network-programming"]
description = "Zenoh-Flow command line tool"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zenoh-flow = {path = "../zenoh-flow"}
zenoh = { git = "https://github.com/eclipse-zenoh/zenoh.git", branch = "master" }
zenoh-util = { git = "https://github.com/eclipse-zenoh/zenoh.git", branch = "master" }
zrpc = { git = "https://github.com/atolab/zenoh-rpc.git", branch = "master" }
znrpc-macros = { git = "https://github.com/atolab/zenoh-rpc.git", branch = "master" }
async-std = { version = "=1.10.0", features = ["attributes"] }
clap = { version = "3.1", features = ["derive"] }
exitfailure = "0.5.1"
failure = "0.1.8"
prettytable-rs = "^0.8"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
base64 = "0.13.0"
derive_more = "0.99.10"
semver = { version = "1.0.4", features = ["serde"]}
rand = "0.8.3"
serde_derive = "1.0.55"
serde = { version = "1.0.55", features = ["derive"] }
serde_yaml = "0.8.13"
serde_json = "1.0.55"
serde-aux = "3.0.1"
log = "0.4"
env_logger = "0.9.0"
git-version = "0.3.4"

# Debian package configuration

[package.metadata.deb]
maintainer = "ADLINK Zenoh team <zenoh@adlink-labs.tech>"
copyright = "2021, ADLINK Technology Inc"
extended-description = "Eclipse Zenoh Flow CLI tool"
license-file = ["../LICENSE", "0"]
depends = "$auto"
section = "utils"
priority = "optional"
assets = [
    # binary
    ["target/release/zfctl", "/usr/bin/zfctl", "755"],
]

# RPM package configuration

[package.metadata.rpm]
package = "zfctl"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
zfctl = { path = "/usr/bin/zfctl" }